### ISSUE TITLE
[Bug] Drop Items inside Quest-related Gatherables; A Thread

### ISSUE THREAD

**Issue by Forthbun** [Yoress/friendly-dollop#109] opened 2020-10-05 03:53 UTC
Use this thread to report loot items inside gatherable quest-related nodes. These things should _not_ have other items inside when interacting with these objects. 

Report Name and object ID

Fertilizer Sack - ID: 700145
Beehive - ID: 700061

**Comment by Yoress** [comment] 2020-10-05 04:31
Duplicate of #27.

**Closed by Yoress** 2020-10-05 04:31 UTC
Labels: duplicate
